[project]
name = "graph-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "fire>=0.7.1",
    "huggingface-hub>=0.36.0",
    "kernels>=0.11.3",
    "lap>=0.5.12",
    "opencv-python>=4.12.0.88",
    "scenedetect>=0.6.7.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers>=4.57.6",
    "ultralytics>=8.4.6",
]

