[project]
name = "graph-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "kernels>=0.11.3",
    "opencv-python>=4.12.0.88",
    "scenedetect>=0.6.7.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers",
]

[tool.uv.sources]
transformers = { path = "../../transformers" }
